FROM node:20.12-alpine

ARG SENTRY_AUTH_TOKEN
ARG SENTRY_URL
ARG VITE_BACKEND_URL
ARG VITE_AMPLITUDE_API_KEY
ARG VITE_VITE_ANALYTICS_KEY
ARG VITE_APP_BASE_LINK
ARG VITE_SENTRY_DSN
ARG VITE_ADSGRAM_BLOCK_ID

ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ENV SENTRY_URL=$SENTRY_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_AMPLITUDE_API_KEY=$VITE_AMPLITUDE_API_KEY
ENV VITE_VITE_ANALYTICS_KEY=$VITE_VITE_ANALYTICS_KEY
ENV VITE_APP_BASE_LINK=$VITE_APP_BASE_LINK
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
ENV VITE_ADSGRAM_BLOCK_ID=$VITE_ADSGRAM_BLOCK_ID

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn install

RUN yarn build

CMD ["yarn", "prod"]
